-- ==========================================
-- 学习系统 Supabase 数据库初始化脚本
-- 请在 Supabase -> SQL Editor 中粘贴并执行以下所有 SQL 语句
-- ==========================================

-- 1. 用户学习文章进度表 (user_progress)
CREATE TABLE IF NOT EXISTS public.user_progress (
  id text NOT NULL, -- 格式如 'module_id__doc_idx'
  user_id uuid NOT NULL DEFAULT auth.uid(),
  done boolean DEFAULT true,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  PRIMARY KEY (user_id, id)
);

-- 开启行级安全策略 (RLS)
ALTER TABLE public.user_progress ENABLE ROW LEVEL SECURITY;

-- 创建 RLS 策略：仅允许经过身份验证的用户管理属于自己的数据
DROP POLICY IF EXISTS "Allow individual read/write access to user_progress" ON public.user_progress;
CREATE POLICY "Allow individual read/write access to user_progress" ON public.user_progress
  FOR ALL
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);


-- 2. 测验历史记录表 (quiz_records)
CREATE TABLE IF NOT EXISTS public.quiz_records (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL DEFAULT auth.uid(),
  module_id text NOT NULL,
  doc_idx integer, -- 可为空（例如刷题或错题模式）
  score integer NOT NULL,
  total integer NOT NULL,
  pct integer NOT NULL,
  time bigint NOT NULL -- 记录时的时间戳
);

-- 开启行级安全策略 (RLS)
ALTER TABLE public.quiz_records ENABLE ROW LEVEL SECURITY;

-- 创建 RLS 策略
DROP POLICY IF EXISTS "Allow individual read/write access to quiz_records" ON public.quiz_records;
CREATE POLICY "Allow individual read/write access to quiz_records" ON public.quiz_records
  FOR ALL
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- [修复3] 为 quiz_records 添加 (user_id, time) 联合唯一约束，支持 upsert onConflict 防重
-- 幂等写法：如约束已存在则跳过
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'quiz_records_user_id_time_unique'
      AND conrelid = 'public.quiz_records'::regclass
  ) THEN
    ALTER TABLE public.quiz_records
      ADD CONSTRAINT quiz_records_user_id_time_unique UNIQUE (user_id, time);
  END IF;
END$$;



-- 3. 刷题数据统计表 (drill_stats)
CREATE TABLE IF NOT EXISTS public.drill_stats (
  qid text NOT NULL,
  user_id uuid NOT NULL DEFAULT auth.uid(),
  total integer DEFAULT 0,
  correct integer DEFAULT 0,
  wrong integer DEFAULT 0,
  last_correct boolean,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  PRIMARY KEY (user_id, qid)
);

-- 开启行级安全策略 (RLS)
ALTER TABLE public.drill_stats ENABLE ROW LEVEL SECURITY;

-- 创建 RLS 策略
DROP POLICY IF EXISTS "Allow individual read/write access to drill_stats" ON public.drill_stats;
CREATE POLICY "Allow individual read/write access to drill_stats" ON public.drill_stats
  FOR ALL
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);


-- 4. 错题本表 (wrong_book)
CREATE TABLE IF NOT EXISTS public.wrong_book (
  qid text NOT NULL,
  user_id uuid NOT NULL DEFAULT auth.uid(),
  details jsonb NOT NULL DEFAULT '{}'::jsonb, -- 包含错误次数、选项快照等
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  PRIMARY KEY (user_id, qid)
);

-- 开启行级安全策略 (RLS)
ALTER TABLE public.wrong_book ENABLE ROW LEVEL SECURITY;

-- 创建 RLS 策略
DROP POLICY IF EXISTS "Allow individual read/write access to wrong_book" ON public.wrong_book;
CREATE POLICY "Allow individual read/write access to wrong_book" ON public.wrong_book
  FOR ALL
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);


-- 5. 宠物状态表 (pet_state)
CREATE TABLE IF NOT EXISTS public.pet_state (
  id text NOT NULL DEFAULT 'pet_state',
  user_id uuid NOT NULL DEFAULT auth.uid(),
  state jsonb NOT NULL DEFAULT '{}'::jsonb,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  PRIMARY KEY (user_id, id)
);

-- 开启行级安全策略 (RLS)
ALTER TABLE public.pet_state ENABLE ROW LEVEL SECURITY;

-- 创建 RLS 策略
DROP POLICY IF EXISTS "Allow individual read/write access to pet_state" ON public.pet_state;
CREATE POLICY "Allow individual read/write access to pet_state" ON public.pet_state
  FOR ALL
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);


-- 6. 宠物修炼事件记录表 (pet_events)
CREATE TABLE IF NOT EXISTS public.pet_events (
  id text NOT NULL,
  user_id uuid NOT NULL DEFAULT auth.uid(),
  event jsonb NOT NULL DEFAULT '{}'::jsonb,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  PRIMARY KEY (user_id, id)
);

-- 开启行级安全策略 (RLS)
ALTER TABLE public.pet_events ENABLE ROW LEVEL SECURITY;

-- 创建 RLS 策略
DROP POLICY IF EXISTS "Allow individual read/write access to pet_events" ON public.pet_events;
CREATE POLICY "Allow individual read/write access to pet_events" ON public.pet_events
  FOR ALL
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);


-- 7. 用户同步状态控制表 (user_sync_status)
CREATE TABLE IF NOT EXISTS public.user_sync_status (
  user_id uuid NOT NULL DEFAULT auth.uid() PRIMARY KEY,
  last_updated_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

-- 开启行级安全策略 (RLS)
ALTER TABLE public.user_sync_status ENABLE ROW LEVEL SECURITY;

-- 创建 RLS 策略
DROP POLICY IF EXISTS "Allow individual read/write access to user_sync_status" ON public.user_sync_status;
CREATE POLICY "Allow individual read/write access to user_sync_status" ON public.user_sync_status
  FOR ALL
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);
